-- Add important student fields for comprehensive admission entry (Windex-style)

ALTER TABLE public.students
ADD COLUMN IF NOT EXISTS admission_form_no TEXT,
ADD COLUMN IF NOT EXISTS admission_type TEXT DEFAULT 'regular' CHECK (admission_type IN ('regular', 'transfer', 're-admission', NULL)),
ADD COLUMN IF NOT EXISTS student_type TEXT DEFAULT 'new' CHECK (student_type IN ('new', 'continuing', NULL)),
ADD COLUMN IF NOT EXISTS father_name TEXT,
ADD COLUMN IF NOT EXISTS mother_name TEXT,
ADD COLUMN IF NOT EXISTS mother_contact VARCHAR(20),
ADD COLUMN IF NOT EXISTS category TEXT CHECK (category IN ('general', 'obc', 'sc', 'st', 'other', NULL)),
ADD COLUMN IF NOT EXISTS religion TEXT,
ADD COLUMN IF NOT EXISTS caste TEXT,
ADD COLUMN IF NOT EXISTS birth_place TEXT,
ADD COLUMN IF NOT EXISTS last_school TEXT,
ADD COLUMN IF NOT EXISTS district TEXT,
ADD COLUMN IF NOT EXISTS society TEXT,
ADD COLUMN IF NOT EXISTS aadhar_no VARCHAR(20),
ADD COLUMN IF NOT EXISTS unique_id TEXT,
ADD COLUMN IF NOT EXISTS pen_no TEXT,
ADD COLUMN IF NOT EXISTS apaar_id TEXT,
ADD COLUMN IF NOT EXISTS fee_mafi_amount NUMERIC(12, 2),
ADD COLUMN IF NOT EXISTS fee_mafi_reason TEXT,
ADD COLUMN IF NOT EXISTS all_fee_mafi BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS is_permanent BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS hostel_student BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS food_provided BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS prev_school_attendance INTEGER,
ADD COLUMN IF NOT EXISTS height TEXT,
ADD COLUMN IF NOT EXISTS weight TEXT,
ADD COLUMN IF NOT EXISTS handicap BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS minority BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS hobby TEXT,
ADD COLUMN IF NOT EXISTS sign_of_identity TEXT,
ADD COLUMN IF NOT EXISTS refer_name TEXT,
ADD COLUMN IF NOT EXISTS father_birth_date DATE,
ADD COLUMN IF NOT EXISTS mother_birth_date DATE,
ADD COLUMN IF NOT EXISTS father_education TEXT,
ADD COLUMN IF NOT EXISTS father_occupation TEXT,
ADD COLUMN IF NOT EXISTS father_designation TEXT,
ADD COLUMN IF NOT EXISTS mother_education TEXT,
ADD COLUMN IF NOT EXISTS mother_occupation TEXT,
ADD COLUMN IF NOT EXISTS mother_designation TEXT,
ADD COLUMN IF NOT EXISTS parents_anniversary DATE,
ADD COLUMN IF NOT EXISTS whatsapp_no VARCHAR(20),
ADD COLUMN IF NOT EXISTS yearly_income NUMERIC(14, 2),
ADD COLUMN IF NOT EXISTS fees_due_date DATE,
ADD COLUMN IF NOT EXISTS account_holder_name TEXT,
ADD COLUMN IF NOT EXISTS bank_name TEXT,
ADD COLUMN IF NOT EXISTS bank_branch TEXT,
ADD COLUMN IF NOT EXISTS bank_ifsc TEXT,
ADD COLUMN IF NOT EXISTS account_no TEXT,
ADD COLUMN IF NOT EXISTS guardian_education TEXT,
ADD COLUMN IF NOT EXISTS guardian_occupation TEXT,
ADD COLUMN IF NOT EXISTS guardian_designation TEXT,
ADD COLUMN IF NOT EXISTS transport_required BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS transport_route TEXT,
ADD COLUMN IF NOT EXISTS transport_pickup_point TEXT;
